[versions]
kotlin = "2.3.0"
detekt = "2.0.0-alpha.2"
cli = "0.3.6"
rng = "1.6"

[libraries]
cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "cli" }
rng-core = { group = "org.apache.commons", name = "commons-rng-core", version.ref = "rng" }
rng-simple = { group = "org.apache.commons", name = "commons-rng-simple", version.ref = "rng" }
rng-client = { group = "org.apache.commons", name = "commons-rng-client-api", version.ref = "rng" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
